spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
      allow-override: true
      override-none: true
      override-system-properties: false
  profiles:
    active: native
server:
  port: 8888